version: '3.7'

services:

  weather_challenge:
    build:
      context: app
      dockerfile: Dockerfile
      target: weather_challenge_dev
    volumes:
      - './:/src'
    ports:
      - 8000:8000
    env_file:
      - app/.env
